name: CD Workflow for auth server

on: push
jobs:
  deploy:
    name: deploy and build with ansible playbook
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - uses: actions/checkout@v2
      - name: Execute playbook
        uses: saubermacherag/ansible-playbook-docker-action@v1.3
        with:
          playbookName: ".ansible/playbooks/playbook.yml"
          inventoryFile: ".ansible/inventory/inventory.cfg"
          extraFile: ".ansible/variables_staging.yml"
          extraVars: "-e keycloak_user=${{ secrets.keycloak_user }} -e keycloak_password=${{ secrets.keycloak_password }}
          -e keycloak_db_host=${{ secrets.keycloak_db_host }} -e keycloak_db_database=${{ secrets.keycloak_db_database }}
          -e keycloak_db_port=${{ secrets.keycloak_db_port }} -e keycloak_db_user=${{ secrets.keycloak_db_user }}
           -e keycloak_db_password=${{ secrets.keycloak_db_password }} -e keycloak_db_maintenance_db=${{ secrets.keycloak_db_maintenance_db }}"
          verbosity: "vvvv"
