name: CD Workflow for auth server

on: push
jobs:
  deploy:
    name: deploy and build with ansible playbook
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Execute playbook
        uses: saubermacherag/ansible-playbook-docker-action@v1.3
        with:
          playbookName: ".ansible/playbooks/playbook.yml"
          inventoryFile: ".ansible/inventory/inventory.cfg"
          extraFile: ".ansible/variables_staging.yml"
          extraVars: "-e keycloak.user=${{ secrets.keycloak_user }} -e keycloak.password=${{ secrets.keycloak_password }}
          -e keycloak.db.host=${{ secrets.keycloak_db_host }} -e keycloak.db.database=${{ secrets.keycloak_db_database }}
           keycloak.db.port=${{ secrets.keycloak_db_port }} keycloak.db.user=${{ secrets.keycloak_db_user }}
           keycloak.db.password=${{ secrets.keycloak_db_password }} keycloak.db.maintenance_db=${{ secrets.keycloak_db_maintenance_db }}"
          verbosity: "vv"
